### ISSUE TITLE
long PATH corruption

### ISSUE THREAD

**Issue by ttamttam** [tschoonj/GTK-for-Windows-Runtime-Environment-Installer#1]
Hello,

I had a very long PATH in my environment.

Unfortunately, gtk2-runtime-2.24.25-2015-01-21-ts-win64) erased it: my path now only contain gtk…

Maybe, this is related to the max lengh of strings in NSIS?

The solution would be to use a special version of NSIS, compiled with a max_string_length of 8192 chars.
http://nsis.sourceforge.net/Special_Builds

**Comment by tschoonj** [comment]
Hi Matthieu,

Thanks for the report. I will switch to this new version of NSIS then for my next build.
