### ISSUE TITLE
How to do UI automation test for application based on GTK-for-Windows runtime?

### ISSUE THREAD

**Issue by zrbruce** [tschoonj/GTK-for-Windows-Runtime-Environment-Installer#12]
Hi, tschoonj:

Some desktop application based on GTK-for-Windows runtime has been developed, but right now UI automation test is needed because the input amount is quit large. At first I tried to get each control's handle so that I can write Windows API program to send messages and manipulate each control. But it seems that I can only get the main window's handle, which is meaningless.

So do you have any advice on this? It would increase the test efficiency by a wide margin. Thank you~

**Comment by tschoonj** [comment]
No idea... sounds like a question for the gtk mailinglist.

**Comment by stuaxo** [comment]
Hm, I guess pywinauto won't work as Gtk doesn't support the right MS accessibility standard (I think).

There were things projects like Sikili and Xpresser to visually find the widgets and press them, not sure what the current state of the art is here, but there probably is a modern equivalent.
