### ISSUE TITLE
libfontconfig-1.dll without configuration

### ISSUE THREAD

**Issue by Tontyna** [tschoonj/GTK-for-Windows-Runtime-Environment-Installer#14]
Sorry to bother you again with a request for missing files, but libfontconfig is quite useless without config files.
Had a look at Alexpux's repo and saw that `fonts.conf` etc. is part of the package scripts and probably the `etc/fonts` folder is created when installed in MSYS2.

Fortunately I detected an appropriate `etc/fonts` folder in my Inkscape installation, though it would be comfortable if this folder was already inlcuded in your ready to use environment.

**Comment by tschoonj** [comment]
I am not sure what this would solve. That folder has never been included and yet you're the first one to mention some missing functionality because of this.

If I just add  `/mingw64/etc/fonts` to the installer, would that be sufficient? How would I test that this works as expected?

**Comment by Tontyna** [comment]
**Concerning nobody ever missing the config files:**

Never missed them, too, until recently, when I tried to implement FreeType rendering via fontconfig/pangoft2/cairo in [WeasyPrint](http://weasyprint.org/), which on Windows, without my patch, renders text via native system fonts. I'm not a Pango expert and not shure what actually happens, but definitely the text rendering suffers, compared to rendering with FreeType and fontconfig libraries.
But fontconfig without configuration feeds Pango with an empty font map and all letters are rendered as nice replacemet rectangles.

BTW: The WeasyPrint installation guide recommends your GTK3-Runtime for Win64 users.

Maybe other users use [cairo's "toy" text API](https://cairographics.org/manual/cairo-text.html#cairo-text.description) or stick to the native system fonts or they copy/paste the `/etc/fonts/` folder (like I did) from their GIMP or Inkscape application. Or they don't use cairo/pango at all...  

**Concerning how to provide default config files for libfontconfig:**

I suppose you build your installer by copying the desired files from an updated MSYS2. So yes, copying the complete `/mingw64/etc/fonts/` folder would be the perfect solution.
I neglected my own MSYS2 for a long time; it's been over a year since I did the last `pacman -Sy` -- or was it `-Su`? -- and never installed pango/cairo/fontconfig [sic!] -- but I expect pacman will update the config files along with the library. The folder looks like this:

```
+ etc\fonts\
   + conf.avail\  
     *.avail
   + conf.d\
     *.conf
     README
   fonts.dtd
   fonts.conf
```

**Comment by tschoonj** [comment]
My /mingw64 directory doesn't contain as much as yours:

```
fonts/
├── conf.d
│   ├── 10-hinting-slight.conf
│   ├── 10-scale-bitmap-fonts.conf
│   ├── 20-unhint-small-vera.conf
│   ├── 30-metric-aliases.conf
│   ├── 40-nonlatin.conf
│   ├── 45-generic.conf
│   ├── 45-latin.conf
│   ├── 49-sansserif.conf
│   ├── 50-user.conf
│   ├── 51-local.conf
│   ├── 60-generic.conf
│   ├── 60-latin.conf
│   ├── 65-fonts-persian.conf
│   ├── 65-nonlatin.conf
│   ├── 69-unifont.conf
│   ├── 80-delicious.conf
│   ├── 90-synthetic.conf
│   └── README
└── fonts.conf

```

Would that be sufficient for you to work with?

**Comment by Tontyna** [comment]
Yes, that's all the `fontconfig` library needs to make me happy.

The folder `conf.avail` is a 'Linux Special' (aka *normal*), not required on Windows, where `conf.d` contains the real files:

```
conf.d/README
[...]
These files are normally installed in ../conf.avail and then symlinked here,
allowing them to be easily installed and then enabled/disabled by adjusting
the symlinks.
```

The `fonts.dtd` is, I guess, for the sake of completeness.

As I said, I snatched my `fonts/` from Inkscape, which probably snatches it from its own multi-platform-make `etc/` folder.

**Comment by tschoonj** [comment]
Ok, I will add support for this in the next update of the installers.

**Comment by Tontyna** [comment]
Thanks a lot!

**Comment by Tontyna** [comment]
Great!
