### ISSUE TITLE
cannot load library Windows 10 / Python 3.6 64 bit

### ISSUE THREAD

**Issue by 77cc33** [tschoonj/GTK-for-Windows-Runtime-Environment-Installer#19]
Hello,

Trying to use your library with python 3.6 64 bit @ windows 10, but getting these errors. Do you have idea where to look for a fix solution?

```
cannot load library 'C:\Program Files\GTK2-Runtime Win64\bin\libcairo-2.dll': error 0x7f

cannot load library 'C:\Program Files\GTK2-Runtime Win64\bin\libcairo-gobject-2.dll': error 0x7f
```

**Comment by tschoonj** [comment]
these things are usually caused by multiple versions of the library or its dependencies being available through PATH.

Have you tried dependency walker?

**Comment by 77cc33** [comment]
1. I updated MS VS Buildtools to the latest version
2. Moved GTK runtime path to the top of the windows PATH list

So problem now solved. 

Thank You!

P.S: I thought it's lib conflict as you talked, but seems it works now even with GTK run time at the bottom of PATH list. Even after reboot. 

Thank You
