### ISSUE TITLE
Libxml++

### ISSUE THREAD

**Issue by Dalan94** [tschoonj/GTK-for-Windows-Runtime-Environment-Installer#2]
I tried to use your GTK+ SDK to build libxml++ but the compilation failed. I managed to build it with the [last official build of GTK+](http://www.gtk.org/download/win64.php) so that may be a problem of compilation flag that you used to build libxml2. If you think that the reason is not due to your SDK, please close the issue.
Furthermore I think that libxml++ can be integrate to your SDK and runtime.

**Comment by tschoonj** [comment]
Hi Dalan,

Can you copy-paste the exact error messages you received?
I will gladly add libxml++ for the next build, which I will make sometime soon.

**Comment by Dalan94** [comment]
make  all-recursive
make[1]: Entering directory `/z/libxml++-2.37.2'
Making all in .
make[2]: Entering directory `/z/libxml++-2.37.2'
depbase=`echo libxml++/relaxngschema.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/sh ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -DLIBXMLPP_BUILD   -I. -I. -I. -mms-bitfields -Ic:/gtk/include/libxml2 -Ic:/gtk/include/glibmm-2.4 -Ic:/gtk/lib/glibmm-2.4/include -Ic:/gtk/include/glib-2.0 -Ic:/gtk/lib/glib-2.0/include -Ic:/gtk/include/sigc++-2.0 -Ic:/gtk/lib/sigc++-2.0/include   -Wall -g -O2 -MT libxml++/relaxngschema.lo -MD -MP -MF $depbase.Tpo -c -o libxml++/relaxngschema.lo libxml++/relaxngschema.cc &&\
	mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -DLIBXMLPP_BUILD -I. -I. -I. -mms-bitfields -Ic:/gtk/include/libxml2 -Ic:/gtk/include/glibmm-2.4 -Ic:/gtk/lib/glibmm-2.4/include -Ic:/gtk/include/glib-2.0 -Ic:/gtk/lib/glib-2.0/include -Ic:/gtk/include/sigc++-2.0 -Ic:/gtk/lib/sigc++-2.0/include -Wall -g -O2 -MT libxml++/relaxngschema.lo -MD -MP -MF libxml++/.deps/relaxngschema.Tpo -c libxml++/relaxngschema.cc  -DDLL_EXPORT -DPIC -o libxml++/.libs/relaxngschema.o
libxml++/relaxngschema.cc:34:62: error: expected ')' before 'ctx'
     RelaxNGSchemaParserContextHolder(xmlRelaxNGParserCtxtPtr ctx): ctx_(ctx) {}
                                                              ^
libxml++/relaxngschema.cc:38:5: error: 'xmlRelaxNGParserCtxtPtr' does not name a type
     xmlRelaxNGParserCtxtPtr ctx_;
     ^
libxml++/relaxngschema.cc: In destructor '{anonymous}::RelaxNGSchemaParserContextHolder::~RelaxNGSchemaParserContextHolder()':
libxml++/relaxngschema.cc:35:47: error: 'ctx_' was not declared in this scope
     ~RelaxNGSchemaParserContextHolder() { if (ctx_) xmlRelaxNGFreeParserCtxt(ctx_); }
                                               ^
libxml++/relaxngschema.cc:35:82: error: 'xmlRelaxNGFreeParserCtxt' was not declared in this scope
     ~RelaxNGSchemaParserContextHolder() { if (ctx_) xmlRelaxNGFreeParserCtxt(ctx_); }
                                                                                  ^
libxml++/relaxngschema.cc: In member function 'virtual void xmlpp::RelaxNGSchema::parse_file(const Glib::ustring&)':
libxml++/relaxngschema.cc:83:57: error: 'xmlRelaxNGNewParserCtxt' was not declared in this scope
   parse_context(xmlRelaxNGNewParserCtxt(filename.c_str()));
                                                         ^
libxml++/relaxngschema.cc: In member function 'virtual void xmlpp::RelaxNGSchema::parse_memory(const Glib::ustring&)':
libxml++/relaxngschema.cc:88:78: error: 'xmlRelaxNGNewMemParserCtxt' was not declared in this scope
   parse_context(xmlRelaxNGNewMemParserCtxt(contents.c_str(), contents.bytes()));
                                                                              ^
libxml++/relaxngschema.cc: In member function 'virtual void xmlpp::RelaxNGSchema::parse_document(const xmlpp::Document*)':
libxml++/relaxngschema.cc:97:81: error: 'xmlRelaxNGNewDocParserCtxt' was not declared in this scope
   parse_context(xmlRelaxNGNewDocParserCtxt(const_cast<xmlDoc*>(document->cobj())));
                                                                                 ^
libxml++/relaxngschema.cc: In member function 'void xmlpp::RelaxNGSchema::parse_context(_xmlRelaxNGParserCtxt*)':
libxml++/relaxngschema.cc:108:50: error: no matching function for call to '{anonymous}::RelaxNGSchemaParserContextHolder::RelaxNGSchemaParserContextHolder(_xmlRelaxNGParserCtxt*&)'
   RelaxNGSchemaParserContextHolder holder(context);
                                                  ^
libxml++/relaxngschema.cc:108:50: note: candidates are:
libxml++/relaxngschema.cc:31:9: note: {anonymous}::RelaxNGSchemaParserContextHolder::RelaxNGSchemaParserContextHolder()
   class RelaxNGSchemaParserContextHolder
         ^
libxml++/relaxngschema.cc:31:9: note:   candidate expects 0 arguments, 1 provided
libxml++/relaxngschema.cc:31:9: note: {anonymous}::RelaxNGSchemaParserContextHolder::RelaxNGSchemaParserContextHolder(const {anonymous}::RelaxNGSchemaParserContextHolder&)
libxml++/relaxngschema.cc:31:9: note:   no known conversion for argument 1 from '_xmlRelaxNGParserCtxt*' to 'const {anonymous}::RelaxNGSchemaParserContextHolder&'
libxml++/relaxngschema.cc:110:43: error: 'xmlRelaxNGParse' was not declared in this scope
   pimpl_->schema = xmlRelaxNGParse(context);
                                           ^
libxml++/relaxngschema.cc: In member function 'void xmlpp::RelaxNGSchema::release_underlying()':
libxml++/relaxngschema.cc:129:34: error: 'xmlRelaxNGFree' was not declared in this scope
     xmlRelaxNGFree(pimpl_->schema);
                                  ^
make[2]: *** [libxml++/relaxngschema.lo] Error 1
make[2]: Leaving directory `/z/libxml++-2.37.2'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/z/libxml++-2.37.2'
make: *** [all] Error 2

**Comment by tschoonj** [comment]
It’s possible I compiled libxml2 without schema support which would explain why this fails. I will look into it.

Thanks


Dr. Tom Schoonjans
Research Fellow

Bundesanstalt für Materialforschung und -prüfung (Federal Institute for Materials Research and Testing)
Richard-Willstätter-Strasse 11, 12489 Berlin
Germany

Telephone +49 (0) 30-8104-5612

Tom.Schoonjans@bam.de<mailto:Tom.Schoonjans@bam.de>
www.bam.de


On 16 Jun 2015, at 15:39, Dalan94 <notifications@github.com<mailto:notifications@github.com>> wrote:


make all-recursive
make[1]: Entering directory /z/libxml++-2.37.2'
Making all in .
make[2]: Entering directory/z/libxml++-2.37.2'
depbase=echo libxml++/relaxngschema.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||';\
/bin/sh ./libtool --tag=CXX --mode=compile g++ -DHAVE_CONFIG_H -DLIBXMLPP_BUILD -I. -I. -I. -mms-bitfields -Ic:/gtk/include/libxml2 -Ic:/gtk/include/glibmm-2.4 -Ic:/gtk/lib/glibmm-2.4/include -Ic:/gtk/include/glib-2.0 -Ic:/gtk/lib/glib-2.0/include -Ic:/gtk/include/sigc++-2.0 -Ic:/gtk/lib/sigc++-2.0/include -Wall -g -O2 -MT libxml++/relaxngschema.lo -MD -MP -MF $depbase.Tpo -c -o libxml++/relaxngschema.lo libxml++/relaxngschema.cc<http://relaxngschema.cc> &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile: g++ -DHAVE_CONFIG_H -DLIBXMLPP_BUILD -I. -I. -I. -mms-bitfields -Ic:/gtk/include/libxml2 -Ic:/gtk/include/glibmm-2.4 -Ic:/gtk/lib/glibmm-2.4/include -Ic:/gtk/include/glib-2.0 -Ic:/gtk/lib/glib-2.0/include -Ic:/gtk/include/sigc++-2.0 -Ic:/gtk/lib/sigc++-2.0/include -Wall -g -O2 -MT libxml++/relaxngschema.lo -MD -MP -MF libxml++/.deps/relaxngschema.Tpo -c libxml++/relaxngschema.cc<http://relaxngschema.cc> -DDLL_EXPORT -DPIC -o libxml++/.libs/relaxngschema.o
libxml++/relaxngschema.cc<http://relaxngschema.cc>:34:62: error: expected ')' before 'ctx'
RelaxNGSchemaParserContextHolder(xmlRelaxNGParserCtxtPtr ctx): ctx_(ctx) {}
^
libxml++/relaxngschema.cc<http://relaxngschema.cc>:38:5: error: 'xmlRelaxNGParserCtxtPtr' does not name a type
xmlRelaxNGParserCtxtPtr ctx_;
^
libxml++/relaxngschema.cc<http://relaxngschema.cc>: In destructor '{anonymous}::RelaxNGSchemaParserContextHolder::~RelaxNGSchemaParserContextHolder()':
libxml++/relaxngschema.cc<http://relaxngschema.cc>:35:47: error: 'ctx_' was not declared in this scope
~RelaxNGSchemaParserContextHolder() { if (ctx_) xmlRelaxNGFreeParserCtxt(ctx_); }
^
libxml++/relaxngschema.cc<http://relaxngschema.cc>:35:82: error: 'xmlRelaxNGFreeParserCtxt' was not declared in this scope
~RelaxNGSchemaParserContextHolder() { if (ctx_) xmlRelaxNGFreeParserCtxt(ctx_); }
^
libxml++/relaxngschema.cc<http://relaxngschema.cc>: In member function 'virtual void xmlpp::RelaxNGSchema::parse_file(const Glib::ustring&)':
libxml++/relaxngschema.cc<http://relaxngschema.cc>:83:57: error: 'xmlRelaxNGNewParserCtxt' was not declared in this scope
parse_context(xmlRelaxNGNewParserCtxt(filename.c_str()));
^
libxml++/relaxngschema.cc<http://relaxngschema.cc>: In member function 'virtual void xmlpp::RelaxNGSchema::parse_memory(const Glib::ustring&)':
libxml++/relaxngschema.cc<http://relaxngschema.cc>:88:78: error: 'xmlRelaxNGNewMemParserCtxt' was not declared in this scope
parse_context(xmlRelaxNGNewMemParserCtxt(contents.c_str(), contents.bytes()));
^
libxml++/relaxngschema.cc<http://relaxngschema.cc>: In member function 'virtual void xmlpp::RelaxNGSchema::parse_document(const xmlpp::Document)':
libxml++/relaxngschema.cc<http://relaxngschema.cc>:97:81: error: 'xmlRelaxNGNewDocParserCtxt' was not declared in this scope
parse_context(xmlRelaxNGNewDocParserCtxt(const_cast<xmlDoc>(document->cobj())));
^
libxml++/relaxngschema.cc<http://relaxngschema.cc>: In member function 'void xmlpp::RelaxNGSchema::parse_context(xmlRelaxNGParserCtxt)':
libxml++/relaxngschema.cc<http://relaxngschema.cc>:108:50: error: no matching function for call to '{anonymous}::RelaxNGSchemaParserContextHolder::RelaxNGSchemaParserContextHolder(_xmlRelaxNGParserCtxt&)'
RelaxNGSchemaParserContextHolder holder(context);
^
libxml++/relaxngschema.cc<http://relaxngschema.cc>:108:50: note: candidates are:
libxml++/relaxngschema.cc<http://relaxngschema.cc>:31:9: note: {anonymous}::RelaxNGSchemaParserContextHolder::RelaxNGSchemaParserContextHolder()
class RelaxNGSchemaParserContextHolder
^
libxml++/relaxngschema.cc<http://relaxngschema.cc>:31:9: note: candidate expects 0 arguments, 1 provided
libxml++/relaxngschema.cc<http://relaxngschema.cc>:31:9: note: {anonymous}::RelaxNGSchemaParserContextHolder::RelaxNGSchemaParserContextHolder(const {anonymous}::RelaxNGSchemaParserContextHolder&)
libxml++/relaxngschema.cc<http://relaxngschema.cc>:31:9: note: no known conversion for argument 1 from '_xmlRelaxNGParserCtxt*' to 'const {anonymous}::RelaxNGSchemaParserContextHolder&'
libxml++/relaxngschema.cc<http://relaxngschema.cc>:110:43: error: 'xmlRelaxNGParse' was not declared in this scope
pimpl->schema = xmlRelaxNGParse(context);
^
libxml++/relaxngschema.cc<http://relaxngschema.cc>: In member function 'void xmlpp::RelaxNGSchema::release_underlying()':
libxml++/relaxngschema.cc<http://relaxngschema.cc>:129:34: error: 'xmlRelaxNGFree' was not declared in this scope
xmlRelaxNGFree(pimpl_->schema);
^
make[2]: *** [libxml++/relaxngschema.lo] Error 1
make[2]: Leaving directory /z/libxml++-2.37.2'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory/z/libxml++-2.37.2'
make: *** [all] Error 2

**Comment by Dalan94** [comment]
Yes it's probably the reason because the problem is that "xmlRelaxNGParserCtxtPtr" is not found and it is protected by "#ifdef LIBXML_SCHEMAS_ENABLED" in the source code of libxml2.
