### ISSUE TITLE
If you use Gtk Runtime 2 than how does Gtk Sharp 2.x work?

### ISSUE THREAD

**Issue by sourceskyboxer** [tschoonj/GTK-for-Windows-Runtime-Environment-Installer#20]
Hello,

Did you try with Gtk Sharp 2.x with Gtk Runtime 2 x64?
If it doesn't work than we need libglibplus.dll for x64 :/

You know Mac and Linux are happy than Windows.  That is so sad.
I will look again if Gtk Runtime 2 x64 requirements with Gtk Sharp 2.x.

**Comment by tschoonj** [comment]
Nope, I haven't tried using Gtk Sharp at all with these runtimes. Also, I have no intention of providing support for Gtk Sharp.

**Comment by sourceskyboxer** [comment]
Okay no problem because it is really hard that important native libraries are very unavailable like libglibplus.dll or any from Gtk Sharp 2.x 

I skip that I use with Gtk Sharp 3.22.x
