### ISSUE TITLE
GTK 2 - bad lib folder structure

### ISSUE THREAD

**Issue by Senketsu** [tschoonj/GTK-for-Windows-Runtime-Environment-Installer#22]
Gtk 2 runtime seems to install with bad folder structure for the pixbuf lib

`.\lib\gdk-pixbuf-2.0\2.10.0\loaders\loaders\[files]`
**should be:**
`.\lib\gdk-pixbuf-2.0\2.10.0\loaders\[files]`

**Comment by tschoonj** [comment]
Thanks for reporting the issue. You are right of course. I will fix this in the next release.

**Comment by Senketsu** [comment]
Thank you and thanks for maintaining this repo. You are a champ.

**Comment by tschoonj** [comment]
Should be fixed in the latest release.

Thanks again for reporting the issue!
