### ISSUE TITLE
Include the header files too

### ISSUE THREAD

**Issue by aduzsardi** [tschoonj/GTK-for-Windows-Runtime-Environment-Installer#27]
Hi,
Thank you for packaging this libraries.
Could you please include the header files too , lots of python modules require the header files also to be able to install them like pycairo,PyGobject

Thank you!

**Comment by tschoonj** [comment]
Hi @aduzsardi 

Header files are really beyond the scope of this project: the goal is to simply offer the necessary files for the runtime.

pycairo and pygobject are quite tricky to compile on Windows: if you need these packages, I strongly recommend you use MSYS2 or Anaconda (the conda-forge channel has them).

**Comment by aduzsardi** [comment]
I also tried MSYS2 but i can't get it work with gstreamer
Thanks for the suggestion , i'll try Anaconda too.
