### ISSUE TITLE
Add gtksourceview4

### ISSUE THREAD

**Issue by hol430** [tschoonj/GTK-for-Windows-Runtime-Environment-Installer#28]
Hi, would it be possible to include the gtksourceview4 package? This would be useful for me as I'm working on some C# bindings for sourceview, and I've been working with gtksourceview4, not 3.

**Comment by tschoonj** [comment]
That shouldn't be a problem. I will do so in the next release.

**Comment by hol430** [comment]
That's awesome, thanks man.

**Comment by tschoonj** [comment]
Just created a new release with gtksourceview4. I tested it briefly and it seems to work but let me know if it somehow doesn't...
