### ISSUE TITLE
Just wondering if you could do a 32 build too?

### ISSUE THREAD

**Issue by anfractuosity** [tschoonj/GTK-for-Windows-Runtime-Environment-Installer#3]
First of all, thanks for the great work, I'm using your 64 bit build at the moment, which works brilliantly!

Just wondering if you could do a 32 bit one too?

**Comment by tschoonj** [comment]
Happy to hear you like the package.

Unfortunately I have no plans really to use a 32-bit package, mostly because I am quite happy with the one provided by [Alexander Shaduri](http://gtk-win.sourceforge.net/home/) though it's quite outdated...

**Comment by anfractuosity** [comment]
Just in case anyone is looking for an up-to-date 32bit GTK, i found msys2 supports GTK 3.16
