### ISSUE TITLE
GTK 3 32 bit support

### ISSUE THREAD

**Issue by seikosantana** [tschoonj/GTK-for-Windows-Runtime-Environment-Installer#31]
Are there any installer available for 32 bit?

**Comment by tschoonj** [comment]
No there aren't. This is 2021, you should never have to use 32-bit software, even on Windows 😀

**Comment by seikosantana** [comment]
Hmmmm i agree but i wish i could let my app run on legacy hardware which is x86 that's not so old 😅

Is there anything blocks why the runtime isn't available for 32 bit? Or they could actually be built and run for 32 bit but it's just deprecated?

**Comment by alexolog** [comment]
Unfortunately, Pidgin for Windows is a 32-bit program and comes with an outdated version of GTK 2 that does not display emoji.  A newer version would be highly appreciated, but it cannot use a 64bit version.

Yes, I know that the original question was about GTK 3 and not 2, but the same reasoning applies to both and I didn't want to open another issue.

**Comment by seikosantana** [comment]
>No there aren't. This is 2021, you should never have to use 32-bit software, even on Windows grinning

The other problem I am having is that I am referencing a library that works only in x86 platform, although the OS is 64 bit.
I have also found the 32 bit runtime. Maybe this can be useful too for anyone else looking for it here.
https://github.com/miegir/GTK-for-Windows-Runtime-Environment-Installer-32

Thanks for your work on the runtime package!

**Comment by the-Arioch** [comment]
Can "GTK Preferences" AKA "GTK theme chooser" be recompiled then? 

The last binary on the original GTK Runtime SF page is 32-bit app which was last compiled against GTK 2.10 in 2008. Since you dropped Win32 builds at all it is no more runnable. Which is a bit sad.
