### ISSUE TITLE
Win 10 SDK issue

### ISSUE THREAD

**Issue by jcfuller** [tschoonj/GTK-for-Windows-Runtime-Environment-Installer#4]
Tom,
  As requested I am posting an issue here in regard to your SDK.

 Your new (Jan 27,2016) SDK upload seems to be working fine on my Win7 64 development box but:
It does not work on Win10.
I had not tried any of your SDK's on Win10 before but do have a successful working environment using various gtk+2/3 32/64 sdks I found around the internet.

I do not have any gtk runtimes installed and no gtk sdk's in my path on either Win7 or Win10.
To compile I supply the include and library directories with -I and -L. (using your pkg-config -> response file)
To run I add the Sdk Path (Your bin directory) to the PATH environment before I shell and run the app.

As I said this procedure works fine on Win7 but not on Win 10.

Compiles fine, no errors or warnings.
With your bin folder in the path I get the attached pop-up when compiled app is run.
If I leave out your bin folder path I get the expected "can't find xxxx.dll"

James

![tom1](https://cloud.githubusercontent.com/assets/1230792/12646409/e1680bc4-c59d-11e5-8095-3a83a19a80b8.jpg)

**Comment by tschoonj** [comment]
Hi James,

Thanks for opening the issue.
I googled a bit and found three possible solutions:

- set the program in compatibility mode with windows 7 (go to the executable in Explorer, right click properties, go to Compatibility)
- open the file with Administrator privileges
- open regedit.exe and look for the `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Windows` key and set it to zero

Let me know if any of this works

**Comment by jcfuller** [comment]
Tom,
  These are not really solutions for me.
  I did try the Win7 compatibility before but it was negative.
  Running As Administrator or mucking about the registry is not an option.
  
  I have a working configuration. It just would have been nice to use a newer build and cut down on the number of sdk's (6) I am using now.


  James

**Comment by tschoonj** [comment]
Even without administrator privileges, you should be able to see (read-only) which value that key has. Could you give this a try?

Thanks!

**Comment by jcfuller** [comment]
Here it is
James

![tom3](https://cloud.githubusercontent.com/assets/1230792/12675289/295ac87c-c657-11e5-8989-6e6210cff0c9.jpg)

**Comment by jcfuller** [comment]
Tom,
  I totally screwed up by trying your build on a Windows Pro Insider Preview, without checking if it worked on the current Windows 10.
It works fine on the current Windows 10 release.

Sorry !

James

**Comment by tschoonj** [comment]
No need to apologize.

Glad to hear things worked out in the end.
