### ISSUE TITLE
build 3.18 possibly not working windows 10

### ISSUE THREAD

**Issue by Ambush80** [tschoonj/GTK-for-Windows-Runtime-Environment-Installer#7]
hi there i have installed 3.18 on my windows machine to test, my apps are developed on kubuntu using the gtksharp 3.18.dlls however the apps do not run with your runtime, i have no idea why and no error messages are given, is it possible that i need to develop with 64bit gtksharp 3 .dlls or is something else going on ?

**Comment by tschoonj** [comment]
Without error messages, I really cannot provide much help I'm afraid. Also I have to admit I don't know the first thing about C# 😢 

You may be better off asking you question in a GtkSharp forum...

**Comment by Ambush80** [comment]
i will try and debug, as far as i can tell xplatt apps should run with your runtime, the origional gtk2.exe for windows worked, so i cant workout why yours isnt ? also i am programing in F# but that shouldnt be an issue, i have also managed to get my own runtime working by building on msys2 however i cannot seem to get them to run outside of msys2, no idea why tbh, i will let you know how the debug goes

**Comment by Ambush80** [comment]
well i think i might have found out why the apps wont work, and it looks like its my fault, as for some reason i ended up building the wrong dll's on my linux box, apparently i built 2.99 instead of 3.22.6 etc i will retest and if i am right close this issue

**Comment by Ambush80** [comment]
well i tested again and this time found some errors in the event viewer, turns out that either i have a corrupted .net 4.5 or windows 10 version of .net 4.5 is incompatible with gtk3 apps targeting mono/.net 4.5,
sory to bother you with this, i will close it now.
