### ISSUE TITLE
GTK+ 3.22 with classical GUI Windows

### ISSUE THREAD

**Issue by HackMemory** [tschoonj/GTK-for-Windows-Runtime-Environment-Installer#8]
Hello!! Can you build Gtk+ 3.22 with classical Windows GUI, without gtkmm and with .lib? I will be very grateful. Tnx!

**Comment by HackMemory** [comment]
And what about 32bit support?

**Comment by tschoonj** [comment]
> Hello!! Can you build Gtk+ 3.22 with classical Windows GUI, without gtkmm and with .lib? I will be very grateful. Tnx!

Hi, I am not sure what you mean by classical Windows GUI: could you elaborate on this? Are you referring to particular theme?

If you need a build without Gtkmm, just fork this repo, remove all C++ libraries from the NSIS installer file and rebuild.

The .lib files I cannot add unfortunately, as they are produced by the Visual Studio LIB utility, which is not a part of the MSYS2 toolchain.

> And what about 32bit support?

Not going to happen, as I have no interest in supporting legacy architectures. However, it should be trivial to create a 32-bit counterpart of my installers, as all the necessary dlls are easily obtainable from MSYS2.
